### ISSUE TITLE
Automatic Fitting

### ISSUE THREAD

**Issue by cparperis** [vivien-walter/iscan#14]
Inbuilt functionality for centering a ROI on an identified track is already super useful - I use it for peak fitting individual particles so I can plot how the imaging contrast is evolving with time. But currently the pixel intensity fitting must be performed frame by frame, sequentially (i.e. click on particle, store fit results, move to next frame. Repeat for every 10th frame in stack...).

If possible, can the intensity profiling be made to auto-fit the particle in a centered ROI throughout an entire stack? It would be really nice if the software did this and just spat out the analysis results for the selected line drawn over the same XY coordinates for every frame in the stack.

**Comment by vivien-walter** [comment]
Function currently implemented in the branch dev_for_chris and will be merged later to master

**Comment by vivien-walter** [comment]
Merged with master
