### ISSUE TITLE
"Complete Path" option drags particle track to top-left hand corner of the screen

### ISSUE THREAD

**Issue by cparperis** [vivien-walter/iscan#15]

**Comment by cparperis** [comment]
Manually clicking on a particle to finish an incomplete, automatically identified track causes a glitch where lots of points in the track are dragged up to the top left of the ROI

**Comment by vivien-walter** [comment]
Problem fixed in the last commit to the master branch. Please double check before closng this thread

**Comment by vivien-walter** [comment]
Problem fixed
